Первый символ в строке сделать заглавным
js-tasks-ru/jsbasic-20220711_drdiz pull request #4
Opened 2022-07-14 07:29 UTC by DoppelGannger

2022-07-14 07:30 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-07-14 19:41 UTC, SinimaWath requested changes

2022-07-14 19:41 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  else return str;
else тут лишний и можно без него:

```
if () {
  return ...;
}

return ...;
```

2022-07-14 19:41 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    return firstUpStr;
Временная переменная не нужна, можно сразу вернуть результат:
`return str.charAt(0).toUpperCase() + str.slice(1)`

2022-07-15 04:50 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-07-15 07:49 UTC, DoppelGannger commented on 1-module/3-task/index.js
> +  else return str;
fix

2022-07-15 07:49 UTC, DoppelGannger commented on 1-module/3-task/index.js
> +    return firstUpStr;
fix

2022-07-15 09:52 UTC, SinimaWath approved these changes

2022-07-15 09:52 UTC, merged